### ISSUE TITLE
Markdown section anchors show up in the TOC

### ISSUE THREAD

**Issue by fedorov** [billryan/gitbook-plugin-etoc#3]
Steps to reproduce: specify user-defined anchors as follows:

```
# My section 1 {#section1}
```

Nice work otherwise, thank you for sharing!

**Comment by billryan** [comment]
Thanks for the bug report. Seems the node package `markdown-toc` does not handle this case well.

**Comment by billryan** [comment]
TOC generated by upstream `markdown-toc` is not flexible and can be only used for markdown, I will find/write another TOC generation helper with HTML to make it generic.

**Comment by aldanor** [comment]
Hit this too, pretty frustrating. Wonder if these (`{#foo-bar}` at the end of the line) could be just stripped manually?

**Comment by aldanor** [comment]
Ok, I think I've fixed it myself (in #8).
