### ISSUE TITLE
it does not work.

### ISSUE THREAD

**Issue by johnny1952** [billryan/gitbook-plugin-etoc#7]
it does not work.
my  md is like :
```
# mock测试指南
*by 李@测试部*
- - - - -
<!-- toc -->

#aaaaaaaaaaaaaaaaaaaaa1
对于分层系统来说，为了测试充分，需要针对每一层进行测试
```

**Comment by billryan** [comment]
What is "it does not work" exactly mean?
The TOC would show only if it meets the [requirement](https://github.com/billryan/gitbook-plugin-etoc#config). It would not show TOC on every page.

**Comment by billryan** [comment]
etoc plugin assumes only one header1, followed by multiple header2 and header3. It is not friendly to show TOC for only one section with header1.

**Comment by billryan** [comment]
Closed as no feedback.
